server:
  port: 8777

spring:
  datasource:
    url: jdbc:mysql://123.56.169.21:3306/linnadb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: linna
    password: d%r2Tz08
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    show-sql: true
  application:
    name: zimug-server-gateway
  cloud:
    # 对服务进行限流
    sentinel:
      transport:
        port: 8719
        dashboard: 192.168.1.60:8774
    # 注册到nacos
    nacos:
      discovery:
        server-addr: 192.168.1.60:8848
    gateway:
      # 开启转发的负载均衡
      discovery:
        locator:
          enabled: true
      # 第一种：配置文件形式转发
      routes:
        # 转发规则名称
        - id: rbsc-service
          # 要跳转的路径 lb://<服务注册名称>
          # uri: http://localhost:8401/
          uri: lb://aservice-rbac
          # 跳转条件
          predicates:
            - name: RbacAuth
              args:
                flag: rbac
          # 自定义过滤器
          filters:
            - name: IPForbid
              args:
                # 配置文件多个参数
                permitIp: 127.0.0.1
                # xxx: xxx

# 认证先关自定义配置
zimug:
  gateway:
    jwt:
      enabled: true   #是否开启JWT登录认证功能
      secret: fjkfaf;afa  # JWT私钥，用于校验JWT令牌的合法性
      expiration: 3600000 #JWT令牌的有效期，用于校验JWT令牌的合法性
      # cookie名称
      header: JWTHeaderName #HTTP请求的Header名称，该Header作为参数传递JWT令牌
      userParamName: username  #用户登录认证用户名参数名称
      pwdParamName: password  #用户登录认证密码参数名称
      useDefaultController: true # 是否使用默认的JwtAuthController
